Feature tagging (#9)
* Wrapping up friday afternoon

* Bringing everything in order

* Moving to signing again

* Look for signtool on runner

* Run job on cmd

* remove gänsefüsse

* Showing the contents of the location

* trying proper set up

* trying proper set up

* Replace call with &

* vcvarsall instead of vcvars64

* running it as a batch script...

* looking for signtool and adding it to the path

* removing the addition to path to see if still works

* small fix to remove warning

* checking git setup on workflow

* checking git setup on workflow

* added checkout

* Some clean up

* Checking runner git config

* creating a new file on the runner to be addde to repo

* Find out where we are on runner

* finding path and fixing sdk install

* Trying to fix signtool installation

* Remove shell:bash from a non-bash step...

* Remove shell:bash from a non-bash step...

* Extending workflow

* Add certificate to workflow

* Adding password to certificate

* Fix ordering of variable declaration

* Testing adding to git in workflow

* Working on writing into repo from runner

* removing signing step

* Add checkout

* Add temp file

* Configuring branches in workflow

* Set url explicitly

* Switching to a fine grain token

* Commit from runner

* Fokus wieder auf signieren

* Fix syntax error

* How do secrets work?

* Back to debugging

* Back to debugging

* Adding test certificate

* Trying with stored certificate

* Adding test certificate

* Adjusting workflow

* Empty password

* Add password

* Adding OfficeSIPS files to repo

* Install msosipx.dll

* Attempt to run regsvr as admin

* Checking C++ libs

* Checking dll registration

* Registration failed, but why

* Use pwsh syntax

* Fix syntax

* Fixing dll path?

* Show dllPath

* Checking validity of location

* Figuring out layout

* Finding the way to msosipx.dll

* Have I found the way?

* The way is near

* maybe it is further away than i thought

* Fix conceptual mistake in pathchoice

* Changing sign file name

* Just registering the dll

* checking registration via bash

* Small change

* Testing pull file that is open

* Update DeleteMe.txt from remote

* Remove deleteMe.txt

* Basic Tagging init

* Start on Tagging UserForm

* end of day clean up

* Some slight efficiency changes to overall subs

* Add UserInput checks for tagging and committing

* Adds some dependency descriptions to the functions, missing: modules

* Change ReadMe.md to check tag retrieval

* Add automated Tag pushing and init work for tag retrieval

* & commitMessage & "

* Commit erstellt von d60157

* ShellCommand Funktion implemeniert und eingebaut - d60157

* Some minor clean up in the vba modules

* A test commit to retrieve an older tagged version

* A first version of TagRetrieval

* Saving Changes to commitaddin.xlsm

* Fix some mistakes in tagger - d60157

* "

* "

* Commit erstellt von d60157"

* Commit erstellt von d60157"

* Commit erstellt von d60157"

* Commit erstellt von d60157"

diff --git a/.github/workflows/Signieren.yml b/.github/workflows/Signieren.yml
--- a/.github/workflows/Signieren.yml
+++ b/.github/workflows/Signieren.yml
@@ -12,17 +12,113 @@ jobs:
     Signieren:
 
         runs-on: windows-latest
+        
 
         steps:
-            # In diesem Job soll dann signtool.exe und die benötigte Software installiert werden
-            - name: build
-              id: build
-              run: |
-                echo "Hier soll signtool.exe installiert werden"
 
-            # Hier wird das Signierskript eingefügt
+            - name: Checkout Repo
+              uses: actions/checkout@v3
+
+            - name: Check Visual C++ 2015-2019 Redistributable (x64)
+              shell: powershell
+              run: |
+                $vcRedist = Get-ItemProperty -Path "HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64" -ErrorAction SilentlyContinue
+                if ($vcRedist -eq $null) {
+                  Write-Host "Visual C++ 2015-2019 Redistributable (x64) is not installed."
+                } else {
+                  Write-Host "Visual C++ 2015-2019 Redistributable (x64) is installed."
+                }
+
+            # In diesem Job soll dann signtool.exe und die benötigte Software installiert/gefunden werden
+            - name: Install Windows SDK
+
+              run: |
+                $sdkPath = Get-Command vswhere | ForEach-Object { $_.Source -replace '\\vswhere\.exe' }
+                Add-Content -Path $env:GITHUB_PATH -Value "$sdkPath\VC\Auxiliary\Build\vcvars64.bat"
+
+            
+#            - name: Certificate Setup
+#              env:
+#                CERTIFICATE_CONTENT: ${{ secrets.TESTSECRET_CMDLINE}}
+#              run: |
+#                echo "$CERTIFICATE_CONTENT" > certificate.pfx
+                
+            - name: Checking network layout
+              shell: bash
+              run: |
+#                ls ./AutomatingSignatures
+#                where msosipx.dll
+
+
+            # Registering OfficeSIPS
+            - name: Office SIPS
+              shell: bash
+              run: |
+                #$dllPath="AutomatingSignatures\msosipx.dll"
+                #Start-Process regsvr32.exe -ArgumentList "/s $dllPath" -Verb RunAs
+                regsvr32.exe AutomatingSignatures/msosipx.dll
+                if [ $? -eq 0 ]; then
+                  echo "Command worked"
+                else
+                  echo "Command failed"
+                fi
+
+
+                
+
+ 
+            #Checking if registration worked
+            - name: Check msosipx.dll registration (assuming it's a COM DLL)
+              shell: powershell
+              run: |
+                  $dllPath = Join-Path $env:GITHUB_WORKSPACE "path\to\msosipx.dll"
+                  $regsvr32Output = Start-Process regsvr32.exe -ArgumentList "/s $dllPath" -PassThru -Wait -NoNewWindow -RedirectStandardOutput output.txt -ErrorAction SilentlyContinue
+                  if ($regsvr32Output.ExitCode -eq 0) {
+                    Write-Host "msosipx.dll registration succeeded."
+                  } else {
+                    Write-Host "msosipx.dll registration failed. Check output.txt for details."
+                    Get-Content output.txt
+                  }
+
+            # Hier wird das Signierskript eingefügt.
             - name: signieren
               id: signieren
               run: |
                 echo "Hier werden dann die gewünschten Dateien signiert."
-                #signtool.exe sign /v /td sha256 /fd sha256 /sha1 $Thumbprint $a
+                # Run vcvarsall.bat to set up the environment
+                cmd /c "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
+
+                # Add the location of signtool to the PATH
+                $env:PATH = $env:PATH + ";" + "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.19041.0\x64"
+
+                # Verify signtool is in the PATH
+                echo "Signtool location:"
+                where.exe signtool
+                
+                signtool sign /f certificate.pfx /p "Swissgrid" /v "TestWorkBook.xlsm"
+              
+
+            # Die nächsten Schritte sind dazu da die Änderungen der vorherigen Schritte bei 
+            # Git zu commiten und pushen. 
+            #
+            # Im Git Setup Schritt werden die Git Einstellungen konfiguriert.
+
+            - name: GitSetup
+              shell: bash
+              run: |
+                #git config --global user.email "benjamin.osullivan@d-fine.com"
+                #git config --global user.name "Ben O'Sullivan"
+            
+            # In diesem Schritt werden die Änderungen zu Git commitet und gepusht.
+            - name: Git Execute
+              env:
+                ACCESS_TOKEN: ${{ secrets.FINEGRAIN_TOKEN }}
+              run: |
+                #touch DeleteMe.txt
+                #git checkout workflow1
+                #git add "CommitAddIn - Copy.xlsm"
+                #git add DeleteMe.txt
+                #git commit -m "Commit from runner"
+                #git remote set-url origin https://username:${ACCESS_TOKEN}@github.com/benosul/EIntWF.git
+
+                #git push -u origin workflow1  # Adjust to your default branch
